# Generated by Django 3.1.2 on 2021-03-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_bad',
            name='uspeh',
            field=models.CharField(default='плохо', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks_good',
            name='uspeh',
            field=models.CharField(default='хорошо', max_length=100),
        ),
    ]
