# Generated by Django 3.1.2 on 2021-03-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_auto_20210311_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks_bad',
            name='task',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks_good',
            name='task',
            field=models.CharField(max_length=100),
        ),
    ]
