# Generated by Django 3.1.2 on 2021-03-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0003_auto_20210312_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks_bad',
            name='category',
            field=models.CharField(default='Проверка утечки данных', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks_good',
            name='category',
            field=models.CharField(default='Проверка утечки данных', max_length=100),
        ),
    ]
