# Generated by Django 3.1.2 on 2021-03-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kursant_fail',
            name='done',
            field=models.CharField(choices=[('Утечка персональных данных', 1), ('Утечка фото/видео', 2), ('Распространение секретных данных', 3)], max_length=100, null=True),
        ),
    ]
