# Generated by Django 3.1.2 on 2021-03-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0006_auto_20210314_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_kursants',
            name='narushen',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='check',
            name='done',
            field=models.CharField(choices=[(1, 'Утечка персональных данных'), (2, 'Утечка фото/видео'), (3, 'Распространение секретных данных'), (4, 'Нарушений не выявлено')], max_length=100, null=True),
        ),
    ]
