# Generated by Django 3.1.2 on 2021-03-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0007_auto_20210316_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='source',
            field=models.CharField(max_length=1000),
        ),
    ]
